### ISSUE TITLE
Přepínač malých a velkých kol

### ISSUE THREAD

**Issue by jakslavik** [davidvavra/duna-valka-assassinu#10]
Administrace by se zjednodušila i přepínač na malé kolo. V malém kole by každý měl automaticky dvě akce (první jménem Mise, druhá Akce libovolné jednotky; pokud se implementuje seznam akcí pro delegáta, dala by se akce libovolné jednotky vybírat ze seznamu) a BV nastavitelné vzorečkem (BV/2 zaokrouhlená nahoru; konkrétní podoba vzorečku se však může v průběhu příprav dalšího běhu změnit).

**Comment by davidvavra** [comment]
Ohledně vzorečku BV/2: Co je BV? BV z minulého kola?

**Comment by jakslavik** [comment]
Přesněji: Fungovalo to tak, že v malém kole člověk dostal bv_male = zaokrouhliNahoru(bv/3), kde bv je počet BV, které by hráč dostal, kdyby bylo velké kolo.  (Za renonc s dělením dvěmi se omlouvám.) Čekám, že v nové verzi to bude stejně/velmi podobně.

**Comment by davidvavra** [comment]
S tím vzorečkem a zaokrouhlováním to bylo implementačně složité. Udělal jsem to tak, že se změna BV propíše do dalších kol stejné velikosti (malé nebo velké). Taky to je takhle flexibilnější, změny se striktně nemusí držet vzorečku.
