### ISSUE TITLE
Změna viditelnosti vyhodnocení

### ISSUE THREAD

**Issue by jakslavik** [davidvavra/duna-valka-assassinu#11]
Po uzavření kola by se změny ve vyhodnocení (např. zprávy pro delegaci apod.) měly ukázat hráčům až ve chvíli, kdy se kolo označí za vyhodnocené, aby všichni dostali nové informace ve stejnou chvíli.

**Comment by davidvavra** [comment]
Jasný, informace se zobrazí až když bude stav kola "Proběhlo", nebudou se ukazovat ve stavu "Vyhodnocování".
