### ISSUE TITLE
Text misí součástí aplikace

### ISSUE THREAD

**Issue by jakslavik** [davidvavra/duna-valka-assassinu#14]
Jednotlivé mise v aplikaci by se mohly rozšířit o "tělo", tedy textové pole s detailnějšími informacemi o konkrétní misi. Toto by se pak mělo objevit i ve výstupu v CSV souboru, ideálně v následujícím formátu:

Podmínka: --- text podmínky ---
volný řádek
--- benefit z mise ---
volný řádek
--- instrukce k vyhodnocení ---

K "instrukcím k vyhodnocení": V novém běhu bude zahrání některých misí mít ještě další efekt, který musí vyhodnocovatelé zpracovat, např. "informace o zahrání této mise se musí objevit ve zprávách" a další.

Z hlediska aplikace asi není potřeba udržovat Podmínku, Benefit a Instrukce zvlášť, nemáme pro to další využití.

**Comment by davidvavra** [comment]
@jakslavik Čistější je udržovat to v DB jako tři položky, bude se s tím i lépe pracovat v admin rozhraní.

Není přehlednější, když to v CSV budou tři sloupečky navíc? Je mi to jedno, klidně tenhle formát, řekni ty jako vyhodnocovač.

**Comment by jakslavik** [comment]
Do toho CSV se v průběhu vyhodnocování ještě přidávají sloupečky s komentáři návrhů/poznámek všech vyhodnocujících. Snažil bych se proto počet sloupečků navíc spíš držet na uzdě. Jediné, co by mělo smysl teoreticky dát zvlášť, jsou ty instrukce, aby se mohlo zvlášť značit vyhodnocenou misi a provedení všech instrukcí; udělal bych to tedy tak a doufal, že v průběhu vyhodnocování nezjistíme, že to byla špatné volba.

**Comment by davidvavra** [comment]
No když už oddělíme instrukce k vyhodnocení, tak mi přijde že mít v jednom sloupečku podmínku a benefit spíš méně přehledné, protože se tam pořád bude opakovat to --- text podmínky --- a --- benefit z mise ---

**Comment by jakslavik** [comment]
To ---text podmínky --- a --- benefit z mise --- jsem myslel jako placeholdery pro skutečný text. :) Ze zkušeností z minulého vyhodnocování není potřeba mít podmínku zvlášť. Konkrétně si to představuju takhle:

```
jméno mise      & tělo mise                                         & instrukce
================================================================================
Bombardování    & Zaútočí na všechny jednotky na zvoleném políčku.  & zprávy
Melanžová orgie & Podmínka: Armáda je v síči.                       &

                  Zvýší morálku armády.
Bombardování    & Zaútočí na všechny jednotky na zvoleném políčku.  & zprávy

```

První řádek jsou (improvizovaná) jména sloupců, ampersand odděluje jednotlivé sloupce. Mise "melanžová orgie" má podmínku, která je explicitně vyznačená slovem Podmínka a oddělená od benefitu prázdným řádkem. Mise Bombardování podmínku nemá, zato obsahuje instrukci, že se informace o něm objeví ve zprávách. Je uvedeno dvakrát pro představu (třeba ho zahrál i někdo jiný), jak se mise s podmínkou zobrazí mezi jinými akcemi. V dokumentu, ve kterém se vyhodnocuje, jsou sloupce často natolik úzké, že se i jen trochu delší texty musí zalamovat, proto ten prázdný řádek na lepší oddělení podmínky od těla. Fakticky jsou popisy akce od hráčů tak obsáhlé, že jeden řádek navíc v typicky dost krátkých textech misí nebude z hlediska přehlednosti problém.

**Comment by davidvavra** [comment]
Jo tak, to jsem špatně pochopil. Takhle to je přehledné, udělám tak.
