### ISSUE TITLE
Nahrávání misí ze souboru

### ISSUE THREAD

**Issue by jakslavik** [davidvavra/duna-valka-assassinu#16]
Bylo by fajn moct nahrávat mise ze souboru. Principiálně je v pořádku činit tak pro každého hráče zvlášť. Jestli se pokoušet o systém, kterému se strčí jeden soubor a ten to příslušně rozstrká jednotlivým hráčům, je k diskusi.

Ze souboru by se rozhodně měly načíst následující údaje (ve verzi pro jednoho hráče):
název mise, klíčové slovo, cena BV, podmínka splnění mise, benefit mise, instrukce ke zpracování, dostupnost na začátku.

Jak jsem zmiňoval v předchozím Issue, není nutné (nemáme pro to žádné využití) Podmínku, Benefit a Instrukce mít v databázi jako sloupce zvlášť, ale samozřejmě na tom netrvám. Podstatné je, aby se pak ve výstupu tyhle věci objevily v jednom sloupci.

**Comment by davidvavra** [comment]
@jakslavik Asi jsi udělal nějakou chybu, tahle issue tu je dvakrát se stejným textem, jednou načítání a podruhé nahrávání misí.

**Comment by davidvavra** [comment]
@jakslavik Jo určitě nahrávat per-hráč, protože v CSV nevíš jaké jsou IDčka hráčů.

Co je dostupnost na začátku? Jestli je po nahrání mise dostupná?

**Comment by jakslavik** [comment]
Přesně tak. Dostupnost na začátku označuje, jestli je mise dostupná hráči už v prvním kole, aby se toto nemuselo doklikávat ručně v admin rozhraní.

Teoreticky by bylo možné tohle vyčíst z klíčového slova: Minule byly ve formátu strom_A_B, kde "strom" je zkratka stromu, ve kterém se mise nachází (např "voj" pro vojenský), "A" byl sloupec (ve smyslu tier), "B" bylo pořadí ve sloupci. Nejvyšší mise v každém stromě měla tedy pokaždé číslo 3_1, mise, které byly k dispozici od začátku, měly 1_B pro B mezi 1 a 4. Nechám k tvému zhodnocení, nakolik je to viable varianta.

**Comment by davidvavra** [comment]
Podle klíčového slova bych to radši nedělal. Flexibilnější je boolean. Protože to znamená "jestli má být dostupný v čas nahrání", ne "na začátku". Můžeš třeba chtít nahrát nějaké mise i v průběhu hry a booleanem se rozhodnout jestli mají být dostupné nebo ne.
