### ISSUE TITLE
AKCE: Chceme následující kategorie akcí:

### ISSUE THREAD

**Issue by davidvavra** [davidvavra/duna-valka-assassinu#3]
- armádní
- špionská
- hrdinská
- mise
(wording ještě poladíme)

U každé z nich by měl být adminem editovatelný maximální počet. Pointa je, že s každou armádou/špionem/hrdinou půjde udělat jedna akce a každý jich může mít jiný počet.

"Mise" bude speciální akce, které defaultně bude mít jeden hráč právě jednu za kolo.

V kontextu KD jsou vlastně všechno "primární akce". Žádné sekundární akce (kterých má hráč "libovolný počet" nechceme.

**Comment by davidvavra** [comment]
OK, můžeme zrušit primární/sekundární akce a budou prostě jenom primární různých typů. 

Půjde pro každého delegáta nastavit počet jednotlivých typů - v každém kole jinak, ok?

A prosím doladit ten wording, než to začnu programovat.

**Comment by HannibalCZ** [comment]
To zní správně. Jen primární akce a mají různý typ. U každého jde nastavit jiné množství, které se může (a bude) kolo od kola měnit.

Doladíme wording s Honzou a dáme vědět.

**Comment by JanVane** [comment]
Napadají mě dva přístupy (preferuji 2.)
1) Pro každé kolo bude mít každý hráč nadefinovaný kolik má akcí z každé kategorie:
- Armáda
- Špion
- Hrdina
- Mise

2) Pro každého hráče vypíšeme list akcí co má pro každé kolo, např:
- Akce První Caladanské Armády
- Akce Třicáté Osmé  Brigády
- Akce Špiona 013
- Akce Paula Atreides
- Akce Mise

Výhoda druhého přístupu je, že máme přímou atribuci akci k elementu ve hře.

**Comment by davidvavra** [comment]
Jo to je docela fajn a dobré UX. Nebyly by teda žádné kategorie akcí, ale pro každou akci by se v admin rozhraní napsal tenhle free text. I to "Libovolná" by se tam napsalo jako free text stejně jako všechno ostatní. OK?

**Comment by JanVane** [comment]
Ano.

**Comment by HannibalCZ** [comment]
Pozor na jeden detail. Je potřeba, aby tohle free text pole se nám dostalo také do exportu jako další sloupec.

**Comment by davidvavra** [comment]
jj s tím počítám

**Comment by davidvavra** [comment]
Hotovo
