### ISSUE TITLE
Oddelujici cara v UI

### ISSUE THREAD

**Issue by jakslavik** [davidvavra/duna-valka-assassinu#30]
Na sheetu s dulezitymi sdelenimi vlady by bylo fajn oddelit jednotlive hrace napr. carou, aby se zjednodusila orientace, komu dulezite sdeleni patri. Podobna featura by se hodila i u misi, kde se pokazde musim nekolikrat presvedcit, jestli knoflik Smazat patri k misi pod nebo k misi nad.

**Comment by davidvavra** [comment]
Dal jsem tam větší mezeru. Ten formulář je nyní jednodušší jak odpadly titulky akcí, koukni. V misích by to čáry spíš zesložitily, přidat taky mezeru?

**Comment by jakslavik** [comment]
Urcite je to lepsi, diky. U misi to snad pomuze taky.

Jak tady, tak u misi a vlastne skoro kdekoli jinde je z hlediska vyhodnocovani dobre to optimalizovat pro pripad "mam full HD rozliseni a okno prohlizece na polovine obrazovky", jelikoz tak to typicky probiha. Na druhe pulce obrazovky je "cokoliv jineho, z ceho ctu informace, co mam menit".
