### ISSUE TITLE
Zmeny ve sloupcich ve vypisu pro vyhodnoceni

### ISSUE THREAD

**Issue by jakslavik** [davidvavra/duna-valka-assassinu#34]
Ve vypisu pro vyhodnoceni se hodi nasledujici zmeny:

- Sloupec "Popis mise" dava informace o misi, pro hrdiny je prazdny. Zmenil bych nazev na popis a do nej pro akce hrdinu dal info pro hrace a (pokud neni prazdne) info pro orgy oddelene radkem s =====, napriklad.
- "Typ akce" ma hodnoty Mise a Jine. Nam k nicemu neni, ze jde o misi vime jiz ze sloupce Titulek. Z vypisu bych ho odstranil.

Nevzpominam si, jak jsme se dohodli pro sloupec "Klicove slovo". V tuhle chvili ma pro mise hodnotu identifikaru (SPEC_1_1 apod), pro jednotky vyplnuje hrac. Pro mise je to esencialne potreba, pro jednotky je to dobre. Pro predstavu, v sestem kole posledniho behu hraci vyuzili klicove slovo k cca 30 akcim z 55 (mise nepocitam), tj. casto. Pro akce jednotek do tohoto jinak nemame co psat - plnou informaci jednotce mame z pole Popis. Pokud by to tedy slo, bylo by fajn zachovat aktualni system, kdy hraci zadavaji klicova slova ke svym akcim.

**Comment by davidvavra** [comment]
Info pro orgy jsem dal do sloupce Instrukce (který se používá u misí)

Klíčové slovo je tedy zpět a je čistě pro informaci od hráčů. Pro interní identifikátor misí je nyní sloupec Identifikátor.
