### ISSUE TITLE
Reálně chceme dát hráčům možnost vybírat z "projektů" (v našem názvosloví to jsou spíš mise, ale to je detail) jen pro jednu akci za kolo.

### ISSUE THREAD

**Issue by davidvavra** [davidvavra/duna-valka-assassinu#4]
Šlo by nastavit, že nabídka pro výběr projektů se hráči zobrazí jen pro akce, které takto označíme? (či prostě pro jednu akci za kolo)?

**Comment by davidvavra** [comment]
Mohl bych přejmenovat projekty na mise, ať to je jasné i pro hráče.

Co zobrazovat vybírátko vždycky u první akce? Přidávání checkboxu u každé akce jestli to je mise nebo ne je trochu komplikace.

**Comment by HannibalCZ** [comment]
Souhlasím:
1) přejmenovat projekty > mise
2) vybírátko bude vždy jen u první akce (v zásadě by to mělo být povinné, nikdy nechcem, aby hráči vybrali něco jiného).

**Comment by davidvavra** [comment]
Hotovo
