### ISSUE TITLE
Hromadný import BV

### ISSUE THREAD

**Issue by HannibalCZ** [davidvavra/duna-valka-assassinu#41]
Definice "záznamem" níže nazývám řádek v csv exportu, který má slovní popis a pak pro každé kolo číselnou hodnotu BV.

už nyní umí BV export do csv, ideálně chceme umět přes podobné csv umět BV také importovat.

Import by měl umět:
- přidat nové záznamy
- smazat existující záznamy
- editovat existující záznamy

prakticky to znamená, že záznam BV potřebuje klíč/id, který se přidá do exportu. 
uživatel (admin), pak typicky začne exportem, upraví, co je potřeba a pak dá import.

**Comment by davidvavra** [comment]
Je to hotovo.

@HannibalCZ Pozor na to, že řádek v tom CSV není záznam v databázi. Záznam v databázi je změna BV pro jedno kolo jednoho hráče. 

Nově ten hromadný import umí:
- editovat BV pro dané kolo: stačí změnit číslo
- smazat BV pro dané kolo: nahradit nějaké číslo 0
- přidat BV pro dané kolo: tam kde byla 0, změnit na jiné číslo

Z toho vyplývá, že pokud to chceš měnit na úrovni řádků v CSV tak:
- editace řádku funguje libovolně
- smazání řádku se nesmí dělat jako smazání řádku, ale do všech BV se musí napsat 0
- přidání řádku se nesmí dělat jako přidání řádku, ale přes appku jako dřív
