### ISSUE TITLE
Hromadný import hrdinů (a armád)

### ISSUE THREAD

**Issue by HannibalCZ** [davidvavra/duna-valka-assassinu#42]
Schopnost přes jedno csv naimportovat hrdiny/armády pro všechny frakce.
Je důležité aby tento import uměl i "editovat", zejména u armád každé kolo updatujeme slovní popis, který obsahuje sílu, počet atd.
Export by měl nově obsahovat id hrdiny/armády, ať jde id použít při importu pro účely "editace"
Případné "mazání" hrdinů v tomto případě spíš není potřeba. Rozhodně by neměla hrdinu mazat pouhá absence v import souboru.

Typický use case jsou:
a) před hrou pro hromadný import
b) během vyhodnocování, kdy chci updatovat pouze armády, konkrétně editovat (udpatovat) jejich popisy.

**Comment by davidvavra** [comment]
@HannibalCZ Odebral jsem import po hráčích. Přidal jsem hromadný export & import. Pokud sloupce "ID jednotky" není vyplněn, bude vytvořena nová jednotka. Pokud je vyplněna, je editována. Mazání přes import nejde.
