### ISSUE TITLE
Změna rozdělení BV v rámci delegace

### ISSUE THREAD

**Issue by jakslavik** [davidvavra/duna-valka-assassinu#5]
V současné verzi aplikace se zadávají BV pro celou delegaci dohromady a pak se jakýmsi vzorečkem dělí mezi oba delegáty s důrazem na vedoucího delegace. Chceme, aby bylo možné zadávat lidem v delegaci BV zvlášť.

**Comment by davidvavra** [comment]
Jasný, ten vzoreček úplně zruším. Co vedoucí delegace, nemám to taky úplně odstranit?

**Comment by jakslavik** [comment]
Osobně myslím, že to nebudeme potřebovat, ale nediskutovali jsme to a probral bych to na příští schůzce.
