### ISSUE TITLE
Změna misí - každá jen jednou

### ISSUE THREAD

**Issue by jakslavik** [davidvavra/duna-valka-assassinu#6]
V současné verzi je třeba odstraňovat již zahrané mise ručně. Čas na administrativu vyhodnocení by se o něco snížil, kdyby se tyto mise odstraňovaly samy.

**Comment by davidvavra** [comment]
Mise bych neodstraňoval, ale skrýval. Jde o skrývání hráčům nebo v admin rozhraní?

**Comment by jakslavik** [comment]
Prioritou je skrývání hráčům, aby nemohli mise brát dvakrát. Skrývání v admin rozhraní by bylo nice to have. Při práci s misemi u adminů se po naplnění nevykreslí obsah okna ihned, což chápu, že se děje, a nenaznačuju, že by se to mělo řešit. V průběhu hry se dostaneme na cca dvojnásobek počátečního počtu misí. Pokud by se ta prodleva měla s větším počtem zhoršovat, bude přidávání nových misí trvat o něco déle.

**Comment by davidvavra** [comment]
Je složité automaticky skrývat a zobrazovat mise hráčům. Je těžké spočítat, že už byla mise splněna (protože to závisí na akcích) plus jestli se má mise objevit závisí na prerekvizitách a to nemáme v systému. Tak jsem udělal filtr + skrývání misí v admin rozhraní. Půjde si všechny mise připravit dopředu a pak jenom jednoduše skrývat/zobrazovat, to nezabere moc času.
