### ISSUE TITLE
Administrace misí - řazení podle delegáta

### ISSUE THREAD

**Issue by jakslavik** [davidvavra/duna-valka-assassinu#8]
V admin modulu jsou mise řazeny podle data přidání. Pro kontrolu, že jsou u hráče mise správně, by bylo hezké, kdyby šly zobrazit mise jen od jednoho delegáta nebo mít možnost je podle delegáta seřadit.

**Comment by davidvavra** [comment]
Řazení podle delegáta je jednoduché udělat.

**Comment by davidvavra** [comment]
Nakonec jsem neudělal řazení, ale filtr. Je to praktičtější.
