### ISSUE TITLE
Management akcí - seznam akcí pro delegáty

### ISSUE THREAD

**Issue by jakslavik** [davidvavra/duna-valka-assassinu#9]
V současné verzi musíme vypisovat akce pro každého delegáta ručně každé kolo. Čas strávený administrativou při vyhodnocení by dost snížilo, kdyby každý delegát měl kromě seznamu misí i seznam akcí (tj. armád a hrdinů s akcí), které ovládá, na jehož základě se určuje délka seznamu akcí (1 na mise + délka seznamu) a vyplňují textové popisky akcí. Organizátor pak jen aktualizuje tenhle seznam.

**Comment by davidvavra** [comment]
Tohle je složitější udělat, co kdyby se ty textové popisky akcí zapisovaly automaticky i do budoucích kol? Nebylo by pak potřeba to psát každé kolo znova, jenom dělat případné změny.

**Comment by jakslavik** [comment]
Ok, i to je pro nás slušná časová úspora. V takovém případě by vyplníme celé jen pro druhé kolo, které stejně vyplňujeme dopředu.

**Comment by davidvavra** [comment]
Jen pro první kolo a do dalších včetně druhého se to předvyplní.

**Comment by davidvavra** [comment]
Je to udělané takhle: počet akcí a titulky akcí se automaticky kopírují do dalších kol stejné velikosti (malé nebo velké).
